####
# @name loginusingAuth0
POST https://dev-lan01lp56onnm2jo.eu.auth0.com/oauth/token
content-type: application/json

{"client_id":"wWbtuuzGEA2ktjs80fty1rVZyhFH7aMh",
"client_secret":"rKYXFhRgpbRwaArzYZzs7GEJColJbTqfBJ_yaRs9_2gZ5HAGtQ5qFAC7p-MCqgXa",
"audience":"recipesid",
"grant_type":"client_credentials"}


####
GET http://localhost:3000/recipes
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ii1yakcwV3VhbmdYSGJaSk91X1RpbCJ9.eyJpc3MiOiJodHRwczovL2Rldi1sYW4wMWxwNTZvbm5tMmpvLmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJ3V2J0dXV6R0VBMmt0anM4MGZ0eTFyVlp5aEZIN2FNaEBjbGllbnRzIiwiYXVkIjoicmVjaXBlc2lkIiwiaWF0IjoxNjc5NDkzMzc3LCJleHAiOjE2Nzk1Nzk3NzcsImF6cCI6IndXYnR1dXpHRUEya3RqczgwZnR5MXJWWnloRkg3YU1oIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.IgonxWmWVcXVuFGD7H_sJuHAmUusvK5PuPVGfrGoS_Wv5m5_UGEofi61R49zDHBhg9a5n519ijwLiMpJzegy_pe7M7VtEici0gQLl55RtGVLHJkRtFqTVWhNoxive0vJ_U7mTgvfMBhhHzkb6-GqAiEIoG7q6-ej7wzNpgKyGL3qenUVkj5ndCGfG8zSSRX0pbJ42m-5UqBYSdWuO5rpOUEe445xxEacwcpnCUvysKZbpIVvSV9K6jpSbVR2vnqxJv9Q69PcX7ELhhkHE3SbWWz1Kd7YUB0-UQgS05i9n56G4sOiGHKK72a_dE021l7ew8_hZBfVHUvg4CGEa1fzMg